version: '3'
services:
  frontend:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    command: sh -c 'cd todo-react && yarn start'
    ports:
      - 8000:3000
    tty: true
  # ... 他のサービスの定義
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: your-database-name
      POSTGRES_USER: your-username
      POSTGRES_PASSWORD: your-password
    ports:
      - "5432:5432"
    networks:
      - my-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - my-network

networks:
  my-network:
